### ISSUE TITLE
Not working on LineageOs because of rooted device

### ISSUE THREAD

**Issue by LeatherMolly** [fengkx/keeplink#2]
I am questioning, why keeplink isn't working on rooted devices a.k.a. LineageOS?
It is a database for collecting links and other things I want to keep in one place, as a user. 

Dear Fengkx can you please explain it to me and if possible make it available to users of non propriary systems.

Thank you in advance for your answer.

**Comment by fengkx** [comment]
I am using a rooted Android device every day. And It even has xposed installed and enabled. I don't see any probelm to use it.

Rather than considering rooted or not or wchich ROM you used, Install latest morden browser is more useful.

**Comment by LeatherMolly** [comment]
Hi there, thanks for your answer. When I open keeplink it says "device rooted + does not have the basic security requirements to run the app".

It diesn't say what is missing, so I thought it got s. th. to do with the root.

So what is missing? How to be able to use your great application?

Thanks in advance
Ole

P.s. I run android 10 with security patches from 5th december 2021. LineageOS 17.1.

Am 20. Dezember 2021 06:23:58 MEZ schrieb fengkx ***@***.***>:

**Comment by fengkx** [comment]
keeplink is a webapp. Are you using the right one?

**Comment by LeatherMolly** [comment]
Hello Feng,

I just saw that your app is a different one. Sorry the app I am refering to is "org.erikjaen.tidylinksv2". So I need to contact him.

Can you erease the issue, or do I need to do it?

All the best to you
Ole

Am 20. Dezember 2021 09:35:27 MEZ schrieb fengkx ***@***.***>:
